# Phase de build
FROM rust:latest as builder

WORKDIR /usr/src/app

COPY . .

# Installation des outils nécessaires pour la compilation de Rust
RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get clean

# Build de l'application Rust
RUN cargo build --release

# Phase d'exécution
FROM debian:bullseye-slim

# Copie du binaire depuis la phase de build
COPY --from=builder /usr/src/app/target/release/task_manager /usr/local/bin/

WORKDIR /usr/local/bin/

CMD ["./task_manager"]
