# Stage 1: Build stage
FROM node:14-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Execution stage
FROM node:14-alpine AS execution

WORKDIR /usr/src/app

# Créer un utilisateur non-root pour l'exécution du serveur web
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

# Copier uniquement les fichiers nécessaires pour l'exécution (build/ et node_modules/)
COPY --from=build /usr/src/app/build ./build
COPY --from=build /usr/src/app/node_modules ./node_modules

EXPOSE 8080

CMD ["node", "build/index.js"]
